CREATE TABLE test.score(
	pid INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(30) NOT NULL,
    kor TINYINT UNSIGNED NULL,
    math TINYINT UNSIGNED NULL,
    eng TINYINT UNSIGNED NULL
);